# Generated by Django 5.2.4 on 2025-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark as featured image for this project'),
        ),
    ]
