# Generated by Django 5.2.4 on 2025-08-08 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='coauthored_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
