# Generated by Django 5.2.4 on 2025-08-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_co_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='co_authors',
        ),
        migrations.AddField(
            model_name='post',
            name='co_authors',
            field=models.CharField(blank=True, help_text='Comma-separated list of co-authors', max_length=255),
        ),
    ]
