# Generated by Django 5.2.4 on 2025-08-07 06:58

import resume.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_resume_github_alter_resume_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pdf_resume',
            field=models.FileField(blank=True, help_text='Upload your resume as PDF', null=True, upload_to=resume.models.image_upload_path),
        ),
    ]
